src/settings/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, SubmitField


class SettingsForm(FlaskForm):
    theme = SelectField("Theme", choices=["Dark", "Light"])
    enable_logging = SelectField("Enable Logging", choices=["Yes", "No"])
    truncate_title = SelectField("Truncate Title", choices=["Yes", "No"])
    layout = SelectField("Layout", choices=["Table", "Card", "Image Overlay Card"])
    mmdb_promotion = SelectField("MMDB Promotion", choices=["Yes", "No"])
    save = SubmitField("Save")

src/anime/routes.py
import os
from datetime import datetime
import platform

from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    send_file,
    url_for,
)
from sqlalchemy import delete

from src import db
from src.anime.backup import (
    export_mmdb_backup,
    import_anilist_anime,
    import_mmdb_backup,
    import_MyAnimeList_anime,
)
from src.anime.forms import AnimeForm, AnimeSearchBar
from src.anime.utils import (
    AnimeHistory,
    get_layout,
    get_settings,
    remove_cover,
    save_picture,
)
from src.home.utils import mmdb_promotion
from src.models import Anime

today_date = datetime.date(datetime.today())

anime = Blueprint("anime", __name__, url_prefix="/anime")


@anime.route("/list/all")
def anime_list():
    anime_list = Anime.query.order_by(Anime.title.name).all()
    settings = get_settings()
    layout = get_layout()
    return render_template(
        f"anime/{layout}",
        title="Anime List",
        current_section="Anime",
        anime_list=anime_list,
        sort_function="All",
        settings=settings,
    )


# Add New Anime
@anime.route("/new", methods=["GET", "POST"])
def new_anime():
    form = AnimeForm()
    if form.validate_on_submit():
        # In linux if DateField is None(0001-01-01) it will be set to 0001-01-01
        if form.start_date.data == None:
            form.start_date.data = "0001-01-01"
        if form.end_date.data == None:
            form.end_date.data = "0001-01-01"
        if form.cover.data:
            picture_file = save_picture(form.cover.data)
        else:
            picture_file = "default-anime.svg"
        anime = Anime(
            title=form.title.data,
            cover=picture_file,
            start_date=form.start_date.data,
            end_date=form.end_date.data,
            episode=form.episode.data,
            status=form.status.data,
            score=form.score.data,
            description=form.description.data,
            genre=form.genre.data,
            tags=form.tags.data,
            notes=form.notes.data,
        )
        db.session.add(anime)
        db.session.commit()
        flash(f"{form.title.data} is added!", "success")
        return redirect(url_for("anime.anime_list"))
    return render_template(
        "anime/create-anime.html",
        title="New Anime",
        form=form,
        legend="New Anime",
        current_section="Anime",
    )


# Update a Anime
@anime.route("/edit/<int:anime_id>", methods=["GET", "POST"])
def edit_anime(anime_id):
    anime = Anime.query.get_or_404(anime_id)
    form = AnimeForm()
    anime_history = AnimeHistory()
    old_name = anime.title
    history = anime_history.get_history(anime.title)
    if form.validate_on_submit():
        # In linux if DateField is None(0001-01-01) it will be set to 0001-01-01
        if form.start_date.data == None:
            form.start_date.data = "0001-01-01"
        if form.end_date.data == None:
            form.end_date.data = "0001-01-01"
        if form.cover.data:
            remove_cover(anime.cover)
            picture_file = save_picture(form.cover.data)
            anime.cover = picture_file
        anime.title = form.title.data
        anime.start_date = form.start_date.data
        anime.end_date = form.end_date.data
        anime.episode = form.episode.data
        anime.status = form.status.data
        anime.score = form.score.data
        anime.description = form.description.data
        anime.genre = form.genre.data
        anime.tags = form.tags.data
        anime.notes = form.notes.data
        db.session.commit()
        anime_history.check_rename(old_name=old_name, new_name=form.title.data)
        anime_history.add_episode(anime.title, form.episode.data)
        flash("Your anime has been updated!", "success")
    elif request.method == "GET":
        form.title.data = anime.title
        form.start_date.data = datetime.strptime(anime.start_date, "%Y-%m-%d").date()
        form.end_date.data = datetime.strptime(anime.end_date, "%Y-%m-%d").date()
        form.episode.data = anime.episode
        form.status.data = anime.status
        form.score.data = str(anime.score)
        form.description.data = anime.description
        form.genre.data = anime.genre
        form.tags.data = anime.tags
        form.notes.data = anime.notes
    return render_template(
        "anime/edit-anime.html",
        title=f"Edit {anime.title}",
        form=form,
        anime=anime,
        legend="Update Anime",
        current_section="Anime",
        history=history,
        platform=platform
    )


# Delete A Anime
@anime.route("/delete/<int:anime_id>", methods=["POST"])
def delete_anime(anime_id):
    anime = Anime.query.get_or_404(anime_id)
    anime_history = AnimeHistory()
    remove_cover(anime.cover)
    db.session.delete(anime)
    db.session.commit()
    anime_history.clear_history(anime.title)
    flash("Your anime has been Obliterated!", "success")
    return redirect(url_for("anime.anime_list"))


# Sort Anime
@anime.route("/list/<string:sort_function>", methods=["GET", "POST"])
def sort_anime(sort_function):
    anime_list = (
        Anime.query.filter_by(status=sort_function).order_by(Anime.title.name).all()
    )
    settings = get_settings()
    layout = get_layout()
    return render_template(
        f"anime/{layout}",
        title=f"{sort_function} Anime",
        anime_list=anime_list,
        sort_function=sort_function,
        current_section="Anime",
        settings=settings,
    )


# Add One episode To The Anime
@anime.route("/add-one-episode/<int:anime_id>")
def add_one_episode(anime_id):
    anime = Anime.query.get_or_404(anime_id)
    anime_history = AnimeHistory()
    anime.episode = anime.episode + 1
    db.session.commit()
    anime_history.add_episode(anime.title, anime.episode)
    return redirect(url_for("anime.anime_list"))


# Searches anime related to given genres in the database
@anime.route("/genre/<string:genre>", methods=["GET"])
def search_genre(genre):
    anime_list = Anime.query.filter(Anime.genre.like(f"%{genre}%")).all()
    settings = get_settings()
    layout = get_layout()
    return render_template(
        f"anime/{layout}",
        title=f"{genre} Genre",
        anime_list=anime_list,
        current_section="Anime",
        settings=settings,
    )


# Searches anime related to given tags in the database
@anime.route("/tags/<string:tag>", methods=["GET"])
def search_tags(tag):
    anime_list = Anime.query.filter(Anime.tags.like(f"%{tag}%")).all()
    settings = get_settings()
    layout = get_layout()
    return render_template(
        f"anime/{layout}",
        title=f"{tag} Tag",
        anime_list=anime_list,
        current_section="Anime",
        settings=settings,
    )


# The path for uploading the file
@anime.route("/import", methods=["GET", "POST"])
def import_anime():
    return render_template(
        "anime/import-anime.html", current_section="Anime", title="Import Anime"
    )


# Imports backup based on file extension
@anime.route("/import/<string:backup>", methods=["GET", "POST"])
def importbackup(backup):
    # check if the method is post
    if request.method == "POST":
        # get the file from the files object
        backup_file = request.files["file"]
        # Checking if no file is sent
        if backup_file.filename == "":
            flash("Choose a file to import!", "danger")
            return redirect(url_for("anime.import_anime"))
        # If file is sent through MMDB form, checking if file name is correct. If correct, then extracting the import
        if (
            backup == "MyMangaDataBase"
            and backup_file.filename.lower().endswith((".zip"))
            and backup_file.filename.startswith(("MMDB-Anime-Export"))
        ):
            # this will secure the file
            backup_file.save(backup_file.filename)
            import_mmdb_backup(backup_file.filename)
        elif (
            backup == "MyAnimeList"
            and backup_file.filename.lower().endswith((".xml"))
            and backup_file.filename.lower().startswith(("animelist"))
        ):
            # this will secure the file
            backup_file.save(backup_file.filename)
            import_MyAnimeList_anime(backup_file.filename)
        elif backup == "AniList" and backup_file.filename.lower() == "gdpr_data.json":
            backup_file.save(backup_file.filename)
            import_anilist_anime(backup_file.filename)
        else:
            flash("Choose correct file to import!", "danger")
            return redirect(url_for("anime.import_anime"))
        return redirect(
            url_for("anime.anime_list")
        )  # Display thsi message after uploading
    return redirect(
        url_for("anime.import_anime")
    )  # Display thsi message after uploading


# Downloads MMDB json export file
@anime.route("/export")
def export():
    export_mmdb_backup()
    return send_file(f"MMDB-Anime-Export-{today_date}.zip")


# Delete Database
@anime.route("/delete/database")
def delete_database():
    delete_db = delete(Anime).where(Anime.id >= 0)
    anime_history = AnimeHistory()
    db.session.execute(delete_db)
    db.session.commit()
    anime_history.clear_all_history()
    for root, _, files in os.walk("src/static/anime_cover/"):
        for file in files:
            # This if block will prevent deletion of default cover image files
            if file not in ("default-manga.svg", "default-anime.svg"):
                os.remove(os.path.join(root, file))
    return redirect(url_for("anime.anime_list"))


# Searches anime in the database
@anime.route("/search", methods=["POST", "GET"])
def search_anime():
    form = AnimeSearchBar()
    settings = get_settings()
    layout = get_layout()
    if form.validate_on_submit():
        anime_list = Anime.query.filter(
            Anime.title.like(f"%{form.search_field.data}%")
        ).all()
        return render_template(
            f"anime/{layout}",

src/home/routes.py
from flask import Blueprint, render_template, request

from src.home.utils import (
    anime_overview_data,
    check_for_update,
    manga_overview_data,
    mmdb_promotion,
)

home = Blueprint("home", __name__)


@home.route("/")
@home.route("/home")
def homepage():
    manga_data = manga_overview_data()
    anime_data = anime_overview_data()
    show_update_modal = check_for_update()
    return render_template(
        "home.html",
        title="Home",
        current_section="Home",
        manga_data=manga_data,
        anime_data=anime_data,
        show_update_modal=show_update_modal,
    )


@home.route("/more")
def more():
    return render_template("more.html", title="More", current_section="More")


@home.route("/credits")
def credits():
    return render_template("credits.html", title="Credits", current_section="More")


@home.before_request
def before_request():
    endpoint = request.endpoint
    action = {
        "home.more": more,
        "home.credits": credits,
    }.get(endpoint, more)

    mmdb_promotion(action)()

src/settings/routes.py
import json
import os

from flask import Blueprint, flash, render_template, request

from src import db
from src.settings.forms import SettingsForm

settings = Blueprint("settings", __name__, url_prefix="/settings")


def create_json_files():
    if not os.path.exists("json"):
        os.mkdir("json")
    if not os.path.exists("json/settings.json"):
        with open("json/settings.json", "w") as f:
            settings = {
                "theme": "Dark",
                "enable_logging": "Yes",
                "truncate_title": "No",
                "layout": "Table",
                "mmdb_promotion": "Yes",
            }
            json.dump(settings, f)
    if not os.path.exists("json/mangalogs.json"):
        with open("json/mangalogs.json", "w") as f:
            json.dump({}, f)
    if not os.path.exists("json/animelogs.json"):
        with open("json/animelogs.json", "w") as f:
            json.dump({}, f)


@settings.route("", methods=["POST", "GET"])
def settingspage():
    with open("json/settings.json", "r") as f:
        json_settings = json.load(f)

    form = SettingsForm()

    if form.validate_on_submit():
        # Theme
        json_settings["theme"] = form.theme.data
        # Logging
        json_settings["enable_logging"] = form.enable_logging.data
        # Truncate Title
        json_settings["truncate_title"] = form.truncate_title.data
        # Layout
        json_settings["layout"] = form.layout.data
        # MMDB Promotion
        json_settings["mmdb_promotion"] = form.mmdb_promotion.data

        with open("json/settings.json", "w") as f:
            json.dump(json_settings, f, indent=4)
        flash("Settings Updated!", "success")
    elif request.method == "GET":
        # Theme
        form.theme.data = json_settings["theme"]
        # Enable Logging
        form.enable_logging.data = json_settings["enable_logging"]
        # Truncate Title
        form.truncate_title.data = json_settings["truncate_title"]
        # Layout
        form.layout.data = json_settings["layout"]
        # MMDB Promotion
        form.mmdb_promotion.data = json_settings["mmdb_promotion"]
    return render_template(
        "settings.html",
        form=form,
        legend="Settings",
        title="Settings",
        current_section="Settings",
    )

src/templates/anime-list.html
{% extends 'layout.html' %}
{% block body %}
<table class="table table-striped table-hover table-responsive mt-5">
    <thead>
        <tr>
            <th scope="col">Cover</th>
            <th scope="col">Title</th>
            <th scope="col">Score</th>
            <th scope="col">Episodes</th>
            <th scope="col">Start Date</th>
            <th scope="col">End Date</th>
            <th scope="col">Status</th>
        </tr>
    </thead>
    <tbody class="table-group-divider">
        <tr>
            <th>1</th>
            <td>Mark</td>
            <td>Otto</td>
            <td>@mdo</td>
            <td>@mdo</td>
            <td>@mdo</td>
            <td>@mdo</td>
        </tr>
        <tr>
            <th>2</th>
            <td>Jacob</td>
            <td>Thornton</td>
            <td>@fat</td>
            <td>@fat</td>
            <td>@fat</td>
            <td>@fat</td>
        </tr>
        <tr>
            <th>3</th>
            <td>Larry</td>
            <td>the Bird</td>
            <td>@twitter</td>
            <td>@twitter</td>
            <td>@twitter</td>
            <td>@twitter</td>
        </tr>
    </tbody>
</table>
{% endblock %}

src/templates/create_edit_manga.html
{% extends "layout.html" %}
{% block body %}
<div>
    <div class="content-section">
        <form action="" method="post" class="m-sm-5 p-sm-5 border border-opacity-25 rounded-4 p-2 mt-3">
            {{ form.hidden_tag() }}
            <fieldset>
                <legend class="border-bottom mb-4">
                    {{ legend }}
                </legend>
                <div class="form mb-3">
                    {{ form.title.label(class="form-label") }}
                    {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                    <p class="text-muted">If the title is more than 100 characters, use first 100 characters</p>
                </div>
                <div class="form mb-3">
                    {{ form.start_date.label(class="form-label") }}
                    {% if form.start_date.errors %}
                    {{ form.start_date(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.start_date.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.start_date(class="form-control form-control-lg") }}
                    {% endif %}
                    <p class="text-muted">If you don't know Start Date, Enter 01-01-0001 in above field</p>
                </div>
                <div class="form mb-3">
                    {{ form.end_date.label(class="form-label") }}
                    {% if form.end_date.errors %}
                    {{ form.end_date(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.end_date.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.end_date(class="form-control form-control-lg") }}
                    {% endif %}
                    <p class="text-muted">If you don't know End Date, Enter 01-01-0001 in above field</p>
                </div>
                <div class="form mb-3">
                    {{ form.volume.label(class="form-label") }}
                    {% if form.volume.errors %}
                    {{ form.volume(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.volume.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.volume(class="form-control form-control-lg") }}
                    {% endif %}
                    <p class="text-muted">If you haven't started the manga or the manga doesn't have any volumes, enter
                        0
                        (zero) in above field</p>
                </div>
                <div class="form mb-3">
                    {{ form.chapter.label(class="form-label") }}
                    {% if form.chapter.errors %}
                    {{ form.chapter(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.chapter.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.chapter(class="form-control form-control-lg") }}
                    {% endif %}
                    <p class="text-muted">If you haven't started the manga, enter 0 (zero) in above field</p>
                </div>
                <div class="form mb-3">
                    {{ form.score.label(class="form-label") }}
                    {% if form.score.errors %}
                    {{ form.score(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.score.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.score(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form mb-3">
                    {{ form.status.label(class="form-label") }}
                    {% if form.status.errors %}
                    {{ form.status(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.status.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.status(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form mb-3 mt-3">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
</div>
{% endblock body %}

src/templates/home.html
{% extends 'layout.html' %}
{% block body %}
<div class="px-3 mt-5">
    <div class="row g-3">
        <!-- Manga Overview -->
        <div class="border rounded col-md-6">
            <h1 class="text-center">Manga Overview</h1>
            <hr>
            <div class="row g-3">
                <div class="col-md-4 text-center">
                    <p>{{ manga_data["manga_len"] }}</p>
                    <p>Total Manga</p>
                </div>
                <div class="col-md-4 text-center">
                    <p>{{ manga_data["manga_chapter_len"] }}</p>
                    <p>Chapter Read</p>
                </div>
                <div class="col-md-4 text-center">
                    <p>{{ manga_data["mean_score"] }}</p>
                    <p>Mean Score</p>
                </div>
            </div>
            <hr>
            <status>
                <h3>Status</h3>
                {% for key, value in manga_data["status"].items() %}
                <p class="fs-5">Total No. of {{ key }} Manga: {{ value }}</p>
                {% endfor %}
            </status>
            <hr>
            <genres>
                <h3>Genres</h3>
                {% for key, value in manga_data["genre"].items() %}
                <p class="fs-5">
                    <a href="{{ url_for('manga.search_genre', genre=key) }}"
                        class="text-decoration-underline text-reset">{{ key
                        }}</a>: {{ value }}
                </p>
                {% endfor %}
            </genres>
            <hr>
            <score>
                <h3>Score</h3>
                {% for key, value in manga_data["score"].items() %}
                <p class="fs-5">{{ key }}: {{ value }}</p>
                {% endfor %}
            </score>
        </div>
        <!-- Anime Overview -->
        <div class="border rounded col-md-6">
            <h1 class="text-center">Anime Overview</h1>
            <hr>
            <div class="row g-3">
                <div class="col-md-4 text-center">
                    <p>{{ anime_data["anime_len"] }}</p>
                    <p>Total Anime</p>
                </div>
                <div class="col-md-4 text-center">
                    <p>{{ anime_data["anime_episode_len"] }}</p>
                    <p>Episodes Watched</p>
                </div>
                <div class="col-md-4 text-center">
                    <p>{{ anime_data["mean_score"] }}</p>
                    <p>Mean Score</p>
                </div>
            </div>
            <hr>
            <status>
                <h3>Status</h3>
                {% for key, value in anime_data["status"].items() %}
                <p class="fs-5">Total No. of {{ key }} Anime: {{ value }}</p>
                {% endfor %}
            </status>
            <hr>
            <genres>
                <h3>Genres</h3>
                {% for key, value in anime_data["genre"].items() %}
                <p class="fs-5"><a href="{{ url_for('anime.search_genre', genre=key) }}"
                        class="text-decoration-underline text-reset">{{
                        key }}</a>: {{ value
                    }}</p>
                {% endfor %}
            </genres>
            <hr>
            <score>
                <h3>Score</h3>
                {% for key, value in anime_data["score"].items() %}
                <p class="fs-5">{{ key }}: {{ value }}</p>
                {% endfor %}
            </score>
        </div>
    </div>
</div>

<!-- Check For Update Modal -->
{% if show_update_modal %}
<script>
    // Trigger the modal using JavaScript
    document.addEventListener('DOMContentLoaded', function () {
        var staticBackdrop = new bootstrap.Modal(document.getElementById('staticBackdrop'));
        staticBackdrop.show();
    });
    function openGithubPage() {
        window.open("https://github.com/EdwinRodger/MyMangaDataBase/releases/latest");
    };
</script>
{% endif %}
<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Update Available!</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                A new version of MyMangaDataBase is released!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Not Now</button>
                <button type="button" class="btn btn-primary" onclick="openGithubPage()">Download</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/layout.html
<!DOCTYPE html>
{% if theme == "Dark" %}
<html lang="en" data-bs-theme="dark">
{% else %}
<html lang="en" data-bs-theme="light">
{% endif %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Title -->
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>MyMangaDataBase</title>
    {% endif %}
    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180"
        href="{{ url_for('static', filename='favicon/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32"
        href="{{ url_for('static', filename='favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16"
        href="{{ url_for('static', filename='favicon/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ url_for('static', filename='favicon/site.webmanifest') }}">
    <!-- Bootstrap 5.3 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
    <!-- Bootstrap Icons/Glyphs -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <!-- Google Font 'Nunito' - https://fonts.google.com/specimen/Nunito -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet">
    <!-- Meta Elements -->
    <meta name="description" content="MyMangaDataBase or MMDB for short is a app to track you manga and anime">
</head>

<style>
    * {
        font-family: 'Nunito', sans-serif;
    }

    td {
        width: 200px;
    }
</style>

<body>
    <nav class="bg-light-subtle">
        <div class="container">
            <header class="d-flex justify-content-center py-3">
                <ul class="nav nav-pills">
                    {% if current_section == "Home" %}
                    <li class="nav-item"><a href="{{ url_for('home.homepage') }}" class="nav-link active"
                            aria-current="page"><i class="bi bi-house"></i> Home</a></li>
                    {% else %}
                    <li class="nav-item"><a href="{{ url_for('home.homepage') }}" class="nav-link"><i
                                class="bi bi-house"></i> Home</a></li>
                    {% endif %}
                    {% if current_section == "Manga" %}
                    <li class="nav-item"><a href="{{ url_for('manga.manga_list') }}" class="nav-link active"
                            aria-current="page"><i class="bi bi-book"></i> Manga List</a></li>
                    {% else %}
                    <li class=" nav-item"><a href="{{ url_for('manga.manga_list') }}" class="nav-link"><i
                                class="bi bi-book"></i> Manga List</a>
                    </li>
                    {% endif %}
                    {% if current_section == "Anime" %}
                    <li class="nav-item"><a href="{{ url_for('anime.anime_list') }}" class="nav-link active"
                            aria-current="page"><i class="bi bi-film"></i> Anime List</a></li>
                    {% else %}
                    <li class=" nav-item"><a href="{{ url_for('anime.anime_list') }}" class="nav-link"><i
                                class="bi bi-film"></i> Anime List</a>
                    </li>
                    {% endif %}
                    {% if current_section == "Settings" %}
                    <li class="nav-item"><a href="{{ url_for('settings.settingspage') }}" class="nav-link active"
                            aria-current="page"><i class="bi bi-gear"></i> Settings</a></li>
                    {% else %}
                    <li class=" nav-item"><a href="{{ url_for('settings.settingspage') }}" class="nav-link"><i
                                class="bi bi-gear"></i> Settings</a></li>
                    {% endif %}
                    {% if current_section == "More" %}
                    <li class="nav-item"><a href="{{ url_for('home.more') }}" class="nav-link active"
                            aria-current="page"><i class="bi bi-three-dots"></i></i> More</a></li>
                    {% else %}
                    <li class=" nav-item"><a href="{{ url_for('home.more') }}" class="nav-link"><i
                                class="bi bi-three-dots"></i> More</a></li>
                    {% endif %}
                </ul>
            </header>
        </div>
    </nav>
    {% block secondHeader %}{% endblock secondHeader %}
    <flashMessage>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, messages in messages %}
        <div class="alert alert-{{ category }} text-center rounded-0">
            {{ messages | safe }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
    </flashMessage>
    {% block body %}{% endblock body %}
</body>

<!-- Masonry -->
<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
<!-- imagesLoaded -->
<script src="https://unpkg.com/imagesloaded@5/imagesloaded.pkgd.min.js"></script>
<!-- Took this script from https://masonry.desandro.com/layout#imagesloaded and https://codepen.io/desandro/pen/MwJoZQ -->
<script>
    // init Masonry
    var grid = document.querySelector('#masonary-id');

    var msnry = new Masonry(grid, {
        itemSelector: '.masonary-class',
        columnWidth: '.masonary-class',
        percentPosition: true
    });

    imagesLoaded(grid).on('progress', function () {
        // layout Masonry after each image loads
        msnry.layout();
    });
</script>

</html>