src/anime/forms.py
import platform

from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms import (
    DateField,
    IntegerField,
    SelectField,
    StringField,
    SubmitField,
    TextAreaField,
)
from wtforms.validators import DataRequired, Length, Optional


class AnimeForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired(), Length(min=2)])
    cover = FileField("Cover Image", validators=[FileAllowed(["jpg", "png"])])
    if platform.system() == "Windows":
        start_date = DateField("Start Date")
        end_date = DateField("End Date")
    else:
        # DateField will allow None which is a Linux specific problem, solved using - https://github.com/wtforms/wtforms/issues/489#issuecomment-1382074627
        start_date = DateField("Start Date", validators=[Optional()])
        end_date = DateField("End Date", validators=[Optional()])
    episode = IntegerField("Episode")
    score = SelectField("Score", choices=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    status = SelectField(
        "Status",
        choices=["Watching", "Completed", "On hold", "Dropped", "Plan to watch"],
    )
    description = TextAreaField("Description")
    genre = StringField("Genre")
    tags = StringField("Tags")
    notes = TextAreaField("Notes")
    submit = SubmitField("Add")
    update = SubmitField("Update")


class AnimeSearchBar(FlaskForm):
    search_field = StringField("Search", validators=[DataRequired(), Length(min=2)])
    search_button = SubmitField("Search")

src/anime/routes.py
import os
from datetime import datetime
import platform

from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    send_file,
    url_for,
)
from sqlalchemy import delete

from src import db
from src.anime.backup import (
    export_mmdb_backup,
    import_anilist_anime,
    import_mmdb_backup,
    import_MyAnimeList_anime,
)
from src.anime.forms import AnimeForm, AnimeSearchBar
from src.anime.utils import (
    AnimeHistory,
    get_layout,
    get_settings,
    remove_cover,
    save_picture,
)
from src.home.utils import mmdb_promotion
from src.models import Anime

today_date = datetime.date(datetime.today())

anime = Blueprint("anime", __name__, url_prefix="/anime")


@anime.route("/list/all")
def anime_list():
    anime_list = Anime.query.order_by(Anime.title.name).all()
    settings = get_settings()
    layout = get_layout()
    return render_template(
        f"anime/{layout}",
        title="Anime List",
        current_section="Anime",
        anime_list=anime_list,
        sort_function="All",
        settings=settings,
    )


# Add New Anime
@anime.route("/new", methods=["GET", "POST"])
def new_anime():
    form = AnimeForm()
    if form.validate_on_submit():
        # In linux if DateField is None(0001-01-01) it will be set to 0001-01-01
        if form.start_date.data == None:
            form.start_date.data = "0001-01-01"
        if form.end_date.data == None:
            form.end_date.data = "0001-01-01"
        if form.cover.data:
            picture_file = save_picture(form.cover.data)
        else:
            picture_file = "default-anime.svg"
        anime = Anime(
            title=form.title.data,
            cover=picture_file,
            start_date=form.start_date.data,
            end_date=form.end_date.data,
            episode=form.episode.data,
            status=form.status.data,
            score=form.score.data,
            description=form.description.data,
            genre=form.genre.data,
            tags=form.tags.data,
            notes=form.notes.data,
        )
        db.session.add(anime)
        db.session.commit()
        flash(f"{form.title.data} is added!", "success")
        return redirect(url_for("anime.anime_list"))
    return render_template(
        "anime/create-anime.html",
        title="New Anime",
        form=form,
        legend="New Anime",
        current_section="Anime",
    )


# Update a Anime
@anime.route("/edit/<int:anime_id>", methods=["GET", "POST"])
def edit_anime(anime_id):
    anime = Anime.query.get_or_404(anime_id)
    form = AnimeForm()
    anime_history = AnimeHistory()
    old_name = anime.title
    history = anime_history.get_history(anime.title)
    if form.validate_on_submit():
        # In linux if DateField is None(0001-01-01) it will be set to 0001-01-01
        if form.start_date.data == None:
            form.start_date.data = "0001-01-01"
        if form.end_date.data == None:
            form.end_date.data = "0001-01-01"
        if form.cover.data:
            remove_cover(anime.cover)
            picture_file = save_picture(form.cover.data)
            anime.cover = picture_file
        anime.title = form.title.data
        anime.start_date = form.start_date.data
        anime.end_date = form.end_date.data
        anime.episode = form.episode.data
        anime.status = form.status.data
        anime.score = form.score.data
        anime.description = form.description.data
        anime.genre = form.genre.data
        anime.tags = form.tags.data
        anime.notes = form.notes.data
        db.session.commit()
        anime_history.check_rename(old_name=old_name, new_name=form.title.data)
        anime_history.add_episode(anime.title, form.episode.data)
        flash("Your anime has been updated!", "success")
    elif request.method == "GET":
        form.title.data = anime.title
        form.start_date.data = datetime.strptime(anime.start_date, "%Y-%m-%d").date()
        form.end_date.data = datetime.strptime(anime.end_date, "%Y-%m-%d").date()
        form.episode.data = anime.episode
        form.status.data = anime.status
        form.score.data = str(anime.score)
        form.description.data = anime.description
        form.genre.data = anime.genre
        form.tags.data = anime.tags
        form.notes.data = anime.notes
    return render_template(
        "anime/edit-anime.html",
        title=f"Edit {anime.title}",
        form=form,
        anime=anime,
        legend="Update Anime",
        current_section="Anime",
        history=history,
        platform=platform
    )


# Delete A Anime
@anime.route("/delete/<int:anime_id>", methods=["POST"])
def delete_anime(anime_id):
    anime = Anime.query.get_or_404(anime_id)
    anime_history = AnimeHistory()
    remove_cover(anime.cover)
    db.session.delete(anime)
    db.session.commit()
    anime_history.clear_history(anime.title)
    flash("Your anime has been Obliterated!", "success")
    return redirect(url_for("anime.anime_list"))


# Sort Anime
@anime.route("/list/<string:sort_function>", methods=["GET", "POST"])
def sort_anime(sort_function):
    anime_list = (
        Anime.query.filter_by(status=sort_function).order_by(Anime.title.name).all()
    )
    settings = get_settings()
    layout = get_layout()
    return render_template(
        f"anime/{layout}",
        title=f"{sort_function} Anime",
        anime_list=anime_list,
        sort_function=sort_function,
        current_section="Anime",
        settings=settings,
    )


# Add One episode To The Anime
@anime.route("/add-one-episode/<int:anime_id>")
def add_one_episode(anime_id):
    anime = Anime.query.get_or_404(anime_id)
    anime_history = AnimeHistory()
    anime.episode = anime.episode + 1
    db.session.commit()
    anime_history.add_episode(anime.title, anime.episode)
    return redirect(url_for("anime.anime_list"))


# Searches anime related to given genres in the database
@anime.route("/genre/<string:genre>", methods=["GET"])
def search_genre(genre):
    anime_list = Anime.query.filter(Anime.genre.like(f"%{genre}%")).all()
    settings = get_settings()
    layout = get_layout()
    return render_template(
        f"anime/{layout}",
        title=f"{genre} Genre",
        anime_list=anime_list,
        current_section="Anime",
        settings=settings,
    )


# Searches anime related to given tags in the database
@anime.route("/tags/<string:tag>", methods=["GET"])
def search_tags(tag):
    anime_list = Anime.query.filter(Anime.tags.like(f"%{tag}%")).all()
    settings = get_settings()
    layout = get_layout()
    return render_template(
        f"anime/{layout}",
        title=f"{tag} Tag",
        anime_list=anime_list,
        current_section="Anime",
        settings=settings,
    )


# The path for uploading the file
@anime.route("/import", methods=["GET", "POST"])
def import_anime():
    return render_template(
        "anime/import-anime.html", current_section="Anime", title="Import Anime"
    )


# Imports backup based on file extension
@anime.route("/import/<string:backup>", methods=["GET", "POST"])
def importbackup(backup):
    # check if the method is post
    if request.method == "POST":
        # get the file from the files object
        backup_file = request.files["file"]
        # Checking if no file is sent
        if backup_file.filename == "":
            flash("Choose a file to import!", "danger")
            return redirect(url_for("anime.import_anime"))
        # If file is sent through MMDB form, checking if file name is correct. If correct, then extracting the import
        if (
            backup == "MyMangaDataBase"
            and backup_file.filename.lower().endswith((".zip"))
            and backup_file.filename.startswith(("MMDB-Anime-Export"))
        ):
            # this will secure the file
            backup_file.save(backup_file.filename)
            import_mmdb_backup(backup_file.filename)
        elif (
            backup == "MyAnimeList"
            and backup_file.filename.lower().endswith((".xml"))
            and backup_file.filename.lower().startswith(("animelist"))
        ):
            # this will secure the file
            backup_file.save(backup_file.filename)
            import_MyAnimeList_anime(backup_file.filename)
        elif backup == "AniList" and backup_file.filename.lower() == "gdpr_data.json":
            backup_file.save(backup_file.filename)
            import_anilist_anime(backup_file.filename)
        else:
            flash("Choose correct file to import!", "danger")
            return redirect(url_for("anime.import_anime"))
        return redirect(
            url_for("anime.anime_list")
        )  # Display thsi message after uploading
    return redirect(
        url_for("anime.import_anime")
    )  # Display thsi message after uploading


# Downloads MMDB json export file
@anime.route("/export")
def export():
    export_mmdb_backup()
    return send_file(f"MMDB-Anime-Export-{today_date}.zip")


# Delete Database
@anime.route("/delete/database")
def delete_database():
    delete_db = delete(Anime).where(Anime.id >= 0)
    anime_history = AnimeHistory()
    db.session.execute(delete_db)
    db.session.commit()
    anime_history.clear_all_history()
    for root, _, files in os.walk("src/static/anime_cover/"):
        for file in files:
            # This if block will prevent deletion of default cover image files
            if file not in ("default-manga.svg", "default-anime.svg"):
                os.remove(os.path.join(root, file))
    return redirect(url_for("anime.anime_list"))


# Searches anime in the database
@anime.route("/search", methods=["POST", "GET"])
def search_anime():
    form = AnimeSearchBar()
    settings = get_settings()
    layout = get_layout()
    if form.validate_on_submit():
        anime_list = Anime.query.filter(
            Anime.title.like(f"%{form.search_field.data}%")
        ).all()
        return render_template(
            f"anime/{layout}",

src/api/anime/routes.py
from flask import Blueprint, request, jsonify

from src.models import Anime
from src.anime.utils import AnimeHistory

from src import db

anime_API = Blueprint("anime_API", __name__, url_prefix="/api/anime")

@anime_API.route("/add", methods=["POST"])
def add_anime():
    data = request.get_json()
    try:
        anime = Anime(
            title=data["title"],
            episode=data["episode"],
            start_date=data["start_date"],
            end_date=data["end_date"],
            score=data["score"],
            status=data["status"],
            description=data["description"],
            genre=data["genre"],
            tags=data["tags"],
            notes=data["notes"],
        )
        db.session.add(anime)
        db.session.commit()
        return jsonify({"message": "Data received"}), 200
    except Exception as e:
        return (
            jsonify({"message": "There is some error in data", "error": str(e)}),
            400,
        )

@anime_API.route("/edit", methods=["PUT"])
def edit_anime():
    data = request.get_json()
    try:
        anime = Anime.query.filter_by(title=data["title"]).first()
        anime_history = AnimeHistory()
        old_name = anime.title
        anime.title = data["title"]
        anime.episode = data["episode"]
        anime.start_date = data["start_date"]
        anime.end_date = data["end_date"]
        anime.score = data["score"]
        anime.status = data["status"]
        anime.description = data["description"]
        anime.genre = data["genre"]
        anime.tags = data["tags"]
        anime.notes = data["notes"]
        db.session.commit()
        anime_history.check_rename(old_name=old_name, new_name=data["title"])
        anime_history.add_episode(anime.title, data["episode"])
        return jsonify({"message": "Data received"}), 200
    except Exception as e:
        return (
            jsonify({"message": "There is some error in data", "error": str(e)}),
            400,
        )

src/home/routes.py
from flask import Blueprint, render_template, request

from src.home.utils import (
    anime_overview_data,
    check_for_update,
    manga_overview_data,
    mmdb_promotion,
)

home = Blueprint("home", __name__)


@home.route("/")
@home.route("/home")
def homepage():
    manga_data = manga_overview_data()
    anime_data = anime_overview_data()
    show_update_modal = check_for_update()
    return render_template(
        "home.html",
        title="Home",
        current_section="Home",
        manga_data=manga_data,
        anime_data=anime_data,
        show_update_modal=show_update_modal,
    )


@home.route("/more")
def more():
    return render_template("more.html", title="More", current_section="More")


@home.route("/credits")
def credits():
    return render_template("credits.html", title="Credits", current_section="More")


@home.before_request
def before_request():
    endpoint = request.endpoint
    action = {
        "home.more": more,
        "home.credits": credits,
    }.get(endpoint, more)

    mmdb_promotion(action)()

src/templates/anime/anime-cards.html
{% extends 'layout.html' %}
{% block secondHeader %}
<!-- Secondary Header -->
<div>
    <header class="d-flex py-3">
        <!-- List Functions -->
        <ul class="nav nav-pills me-auto ms-2">
            <li class="nav-item"><a href="{{ url_for('anime.new_anime') }}" class="nav-link"><i class="bi bi-book"></i>
                    Add Anime</a></li>
            <li class="nav-item"><a href="{{ url_for('anime.import_anime') }}" class="nav-link"><i
                        class="bi bi-database-down"></i> Import</a></li>
            <li class="nav-item"><a href="{{ url_for('anime.export') }}" class="nav-link"><i
                        class="bi bi-database-up"></i> Export</a></li>
        </ul>
        <!-- Sort Functions -->
        <ul class="nav nav-pills mx-auto">
            {% if sort_function == "All" %}
            <li class="nav-item"><a href="{{ url_for('anime.anime_list') }}" class="nav-link active"
                    aria-current="page">All</a></li>
            {% else %}
            <li class="nav-item"><a href="{{ url_for('anime.anime_list') }}" class="nav-link">All</a></li>
            {% endif %}
            {% if sort_function == "Watching" %}
            <li class="nav-item"><a href="{{ url_for('anime.sort_anime', sort_function = 'Watching') }}"
                    class="nav-link active" aria-current="page">Watching</a></li>
            {% else %}
            <li class="nav-item"><a href="{{ url_for('anime.sort_anime', sort_function = 'Watching') }}"
                    class="nav-link">Watching</a></li>
            {% endif %}
            {% if sort_function == "Completed" %}
            <li class="nav-item"><a href="{{ url_for('anime.sort_anime', sort_function = 'Completed') }}"
                    class="nav-link active" aria-current="page">Completed</a></li>
            {% else %}
            <li class="nav-item"><a href="{{ url_for('anime.sort_anime', sort_function = 'Completed') }}"
                    class="nav-link">Completed</a></li>
            {% endif %}
            {% if sort_function == "On hold" %}
            <li class="nav-item"><a href="{{ url_for('anime.sort_anime', sort_function = 'On hold') }}"
                    class="nav-link active" aria-current="page">On Hold</a></li>
            {% else %}
            <li class="nav-item"><a href="{{ url_for('anime.sort_anime', sort_function = 'On hold') }}"
                    class="nav-link">On Hold</a></li>
            {% endif %}
            {% if sort_function == "Dropped" %}
            <li class="nav-item"><a href="{{ url_for('anime.sort_anime', sort_function = 'Dropped') }}"
                    class="nav-link active" aria-current="page">Dropped</a></li>
            {% else %}
            <li class="nav-item"><a href="{{ url_for('anime.sort_anime', sort_function = 'Dropped') }}"
                    class="nav-link">Dropped</a></li>
            {% endif %}
            {% if sort_function == "Plan to watch" %}
            <li class="nav-item"><a href="{{ url_for('anime.sort_anime', sort_function = 'Plan to watch') }}"
                    class="nav-link active" aria-current="page">Plan To Watch</a></li>
            {% else %}
            <li class="nav-item"><a href="{{ url_for('anime.sort_anime', sort_function = 'Plan to watch') }}"
                    class="nav-link">Plan To Watch</a></li>
            {% endif %}
        </ul>
        <!-- Search Bar -->
        <form method="POST" action="{{ url_for('anime.search_anime')}}" class="d-flex ms-auto me-2">
            {{ anime_navsearch.hidden_tag() }}
            {{ anime_navsearch.search_field(class="form-control mx-1", placeholder=anime_title) }}
            {{ anime_navsearch.search_button(class="btn btn-outline-primary") }}
        </form>
    </header>
</div>
{% endblock %}

<!-- Flash messages go here which comes from layout.html -->

{% block body %}
<!-- Cards -->
{% if settings["layout"] == "Card" %}
<div id="masonary-id" class="row row-cols-3 g-4 ms-5 me-5 justify-content-center"
    data-masonry="{'percentPosition': true}">
    {% for anime in anime_list %}
    <div class="col masonary-class">
        <div class="card" style="max-width: 540px;">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="{{ url_for('static', filename='anime_cover/' + anime.cover) }}"
                        class="img-fluid rounded-start" alt="Anime Cover">
                </div>
                <div class="col-md-8">
                    <div class="card-body pb-0">
                        {% if settings["truncate_title"] == "Yes" %}
                        <h5 class="card-title text-truncate"><a class="text-decoration-underline text-reset"
                                href="{{ url_for('anime.edit_anime', anime_id=anime.id) }}">
                                {{ anime.title }}
                            </a></h5>
                        {% else %}
                        <h5 class="card-title"><a class="text-decoration-underline text-reset"
                                href="{{ url_for('anime.edit_anime', anime_id=anime.id) }}">
                                {{ anime.title }}
                            </a></h5>
                        {% endif %}
                        <p class="card-text">
                            Score: {{ anime.score }}
                        </p>
                        <p class="card-text">
                            Episodes:
                            <a href="{{ url_for('anime.add_one_episode', anime_id=anime.id) }}"
                                class="text-decoration-underline text-reset">
                                {{ anime.episode }}
                            </a>
                        </p>
                        <p class="card-text">
                            Start Date:
                            {% if anime.start_date == "0001-01-01" %}
                            -
                            {% else %}
                            {{ anime.start_date }}
                            {% endif %}
                        </p>
                        <p class="card-text">
                            End Date:
                            {% if anime.end_date == "0001-01-01" %}
                            -
                            {% else %}
                            {{ anime.end_date }}
                            {% endif %}
                        </p>
                        <p class="card-text">Status: {{ anime.status }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<div class="container">
    <div id="masonary-id" class="row row-cols-1 row-cols-md-3" data-masonry='{"percentPosition": true }'>
        {% for anime in anime_list %}
        <div class="col my-2 masonary-class">
            <div class="card p-0 text-bg-dark" style="max-width: 540px; overflow: hidden;">
                <img src="{{ url_for('static', filename='anime_cover/' + anime.cover) }}" class="img-fluid row-md-4"
                    alt="Anime Cover" style="filter:blur(5px); -webkit-filter:blur(5px);">
                <div class="card-img-overlay" style="background-color: rgba(0,0,0, 0.4);">
                    <div class="card-body pb-0">
                        {% if settings["truncate_title"] == "Yes" %}
                        <h5 class="card-title text-truncate"><a class="text-decoration-underline text-reset"
                                href="{{ url_for('anime.edit_anime', anime_id=anime.id) }}">
                                {{ anime.title }}
                            </a></h5>
                        {% else %}
                        <h5 class="card-title"><a class="text-decoration-underline text-reset"
                                href="{{ url_for('anime.edit_anime', anime_id=anime.id) }}">
                                {{ anime.title }}
                            </a></h5>
                        {% endif %}
                        <p class="card-text">
                            Score: {{ anime.score }}
                        </p>
                        <p class="card-text">
                            Episodes:
                            <a href="{{ url_for('anime.add_one_episode', anime_id=anime.id) }}"
                                class="text-decoration-underline text-reset">
                                {{ anime.episode }}
                            </a>
                        </p>
                        <p class="card-text">
                            Start Date:
                            {% if anime.start_date == "0001-01-01" %}
                            -
                            {% else %}
                            {{ anime.start_date }}
                            {% endif %}
                        </p>
                        <p class="card-text">
                            End Date:
                            {% if anime.end_date == "0001-01-01" %}
                            -
                            {% else %}
                            {{ anime.end_date }}
                            {% endif %}
                        </p>
                        <p class="card-text">Status: {{ anime.status }}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}
{% endblock %}

src/templates/anime/anime-list.html
{% extends 'layout.html' %}
{% block secondHeader %}
<!-- Secondary Header -->
<div>
    <header class="d-flex py-3">
        <!-- List Functions -->
        <ul class="nav nav-pills me-auto ms-2">
            <li class="nav-item"><a href="{{ url_for('anime.new_anime') }}" class="nav-link"><i class="bi bi-book"></i>
                    Add Anime</a></li>
            <li class="nav-item"><a href="{{ url_for('anime.import_anime') }}" class="nav-link"><i
                        class="bi bi-database-down"></i> Import</a></li>
            <li class="nav-item"><a href="{{ url_for('anime.export') }}" class="nav-link"><i
                        class="bi bi-database-up"></i> Export</a></li>
        </ul>
        <!-- Sort Functions -->
        <ul class="nav nav-pills mx-auto">
            {% if sort_function == "All" %}
            <li class="nav-item"><a href="{{ url_for('anime.anime_list') }}" class="nav-link active"
                    aria-current="page">All</a></li>
            {% else %}
            <li class="nav-item"><a href="{{ url_for('anime.anime_list') }}" class="nav-link">All</a></li>
            {% endif %}
            {% if sort_function == "Watching" %}
            <li class="nav-item"><a href="{{ url_for('anime.sort_anime', sort_function = 'Watching') }}"
                    class="nav-link active" aria-current="page">Watching</a></li>
            {% else %}
            <li class="nav-item"><a href="{{ url_for('anime.sort_anime', sort_function = 'Watching') }}"
                    class="nav-link">Watching</a></li>
            {% endif %}
            {% if sort_function == "Completed" %}
            <li class="nav-item"><a href="{{ url_for('anime.sort_anime', sort_function = 'Completed') }}"
                    class="nav-link active" aria-current="page">Completed</a></li>
            {% else %}
            <li class="nav-item"><a href="{{ url_for('anime.sort_anime', sort_function = 'Completed') }}"
                    class="nav-link">Completed</a></li>
            {% endif %}
            {% if sort_function == "On hold" %}
            <li class="nav-item"><a href="{{ url_for('anime.sort_anime', sort_function = 'On hold') }}"
                    class="nav-link active" aria-current="page">On Hold</a></li>
            {% else %}
            <li class="nav-item"><a href="{{ url_for('anime.sort_anime', sort_function = 'On hold') }}"
                    class="nav-link">On Hold</a></li>
            {% endif %}
            {% if sort_function == "Dropped" %}
            <li class="nav-item"><a href="{{ url_for('anime.sort_anime', sort_function = 'Dropped') }}"
                    class="nav-link active" aria-current="page">Dropped</a></li>
            {% else %}
            <li class="nav-item"><a href="{{ url_for('anime.sort_anime', sort_function = 'Dropped') }}"
                    class="nav-link">Dropped</a></li>
            {% endif %}
            {% if sort_function == "Plan to watch" %}
            <li class="nav-item"><a href="{{ url_for('anime.sort_anime', sort_function = 'Plan to watch') }}"
                    class="nav-link active" aria-current="page">Plan To Watch</a></li>
            {% else %}
            <li class="nav-item"><a href="{{ url_for('anime.sort_anime', sort_function = 'Plan to watch') }}"
                    class="nav-link">Plan To Watch</a></li>
            {% endif %}
        </ul>
        <!-- Search Bar -->
        <form method="POST" action="{{ url_for('anime.search_anime')}}" class="d-flex ms-auto me-2">
            {{ anime_navsearch.hidden_tag() }}
            {{ anime_navsearch.search_field(class="form-control mx-1", placeholder=anime_title) }}
            {{ anime_navsearch.search_button(class="btn btn-outline-primary") }}
        </form>
    </header>
</div>
{% endblock %}

<!-- Flash messages go here which comes from layout.html -->

{% block body %}
<!-- Table -->
<div class="table-responsive">
    <table class="table table-striped table-hover align-middle mt-4">
        <thead>
            <tr class="text-center">
                <th scope="col">Cover</th>
                <th scope="col">Title</th>
                <th scope="col">Score</th>
                <th scope="col">Episodes</th>
                <th scope="col">Start Date</th>
                <th scope="col">End Date</th>
                <th scope="col">Status</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            {% for anime in anime_list %}
            <tr class="text-center">
                <cover>
                    <td>
                        <img src="{{ url_for('static', filename='anime_cover/' + anime.cover) }}" alt="Anime Cover"
                            style="height: 15vh;">
                    </td>
                </cover>
                {% if truncate_title == "Yes" %}
                <!-- 25vw was very small (like 1 letter) in smaller devices so min-width is used to show starting of the title at least -->
                <td class="text-truncate" style="max-width: 25vw; min-width: 200px" data-bs-toggle="tooltip">
                    <a class="text-decoration-underline text-reset"
                        href="{{ url_for('anime.edit_anime', anime_id=anime.id) }}">
                        {{ anime.title }}
                    </a>
                </td>
                {% else %}
                <td>
                    <a class="text-decoration-underline text-reset"
                        href="{{ url_for('anime.edit_anime', anime_id=anime.id) }}">
                        {{ anime.title }}
                    </a>
                </td>
                {% endif %}
                <td>{{ anime.score }}</td>
                {% if anime.episode == 0 %}
                <td>-</td>
                {% else %}
                <td>
                    <a href="{{ url_for('anime.add_one_episode', anime_id=anime.id) }}"
                        class="text-decoration-underline text-reset">
                        {{ anime.episode }}
                    </a>
                </td>
                {% endif %}
                {% if anime.start_date == "0001-01-01" %}
                <td>-</td>
                {% else %}
                <td>{{ anime.start_date }}</td>
                {% endif %}
                {% if anime.end_date == "0001-01-01" %}
                <td>-</td>
                {% else %}
                <td>{{ anime.end_date }}</td>
                {% endif %}
                <td>{{ anime.status }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}