src/manga/forms.py
import platform

from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms import (
    DateField,
    IntegerField,
    SelectField,
    StringField,
    SubmitField,
    TextAreaField,
)
from wtforms.validators import DataRequired, Length, Optional


class MangaForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired(), Length(min=2)])
    cover = FileField("Cover Image", validators=[FileAllowed(["jpg", "png"])])
    if platform.system() == "Windows":
        start_date = DateField("Start Date")
        end_date = DateField("End Date")
    else:
        # DateField will allow None which is a Linux specific problem, solved using - https://github.com/wtforms/wtforms/issues/489#issuecomment-1382074627
        start_date = DateField("Start Date", validators=[Optional()])
        end_date = DateField("End Date", validators=[Optional()])
    volume = IntegerField("Volume")
    chapter = IntegerField("Chapter")
    score = SelectField("Score", choices=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    status = SelectField(
        "Status",
        choices=["Reading", "Completed", "On hold", "Dropped", "Plan to read"],
    )
    description = TextAreaField("Description")
    genre = StringField("Genre")
    tags = StringField("Tags")
    author = StringField("Author")
    artist = StringField("Artist")
    notes = TextAreaField("Notes")
    submit = SubmitField("Add")
    update = SubmitField("Update")


class MangaSearchBar(FlaskForm):
    search_field = StringField("Search", validators=[DataRequired(), Length(min=2)])
    search_button = SubmitField("Search")

src/api/manga/routes.py
from flask import Blueprint, request, jsonify

from src.models import Manga
from src.manga.utils import MangaHistory

from src import db

manga_API = Blueprint("manga_API", __name__, url_prefix="/api/manga")

@manga_API.route("/add", methods=["POST"])
def add_manga():
    data = request.get_json()
    try:
        manga = Manga(
            title=data["title"],
            start_date=data["start_date"],
            end_date=data["end_date"],
            volume=data["volume"],
            chapter=data["chapter"],
            status=data["status"],
            score=data["score"],
            description=data["description"],
            genre=data["genre"],
            tags=data["tags"],
            author=data["author"],
            artist=data["artist"],
            notes=data["notes"],
        )
        db.session.add(manga)
        db.session.commit()
        return jsonify({"message": "Data received"}), 200
    except Exception as e:
        return (
            jsonify({"message": "There is some error in data", "error": str(e)}),
            400,
        )

@manga_API.route("/edit", methods=["PUT"])
def edit_manga():
    data = request.get_json()
    try:
        manga = Manga.query.filter_by(title=data["title"]).first()
        manga_history = MangaHistory()
        old_name = manga.title
        manga.title = data["title"]
        manga.start_date = data["start_date"]
        manga.end_date = data["end_date"]
        manga.volume = data["volume"]
        manga.chapter = data["chapter"]
        manga.status = data["status"]
        manga.score = data["score"]
        manga.description = data["description"]
        manga.genre = data["genre"]
        manga.tags = data["tags"]
        manga.author = data["author"]
        manga.artist = data["artist"]
        manga.notes = data["notes"]
        db.session.commit()
        manga_history.check_rename(old_name=old_name, new_name=data["title"])
        manga_history.add_chapter(manga.title, data["chapter"])
        return jsonify({"message": "Data received"}), 200
    except Exception as e:
        return (
            jsonify({"message": "There is some error in data", "error": str(e)}),
            400,
        )

src/home/routes.py
from flask import Blueprint, render_template, request

from src.home.utils import (
    anime_overview_data,
    check_for_update,
    manga_overview_data,
    mmdb_promotion,
)

home = Blueprint("home", __name__)


@home.route("/")
@home.route("/home")
def homepage():
    manga_data = manga_overview_data()
    anime_data = anime_overview_data()
    show_update_modal = check_for_update()
    return render_template(
        "home.html",
        title="Home",
        current_section="Home",
        manga_data=manga_data,
        anime_data=anime_data,
        show_update_modal=show_update_modal,
    )


@home.route("/more")
def more():
    return render_template("more.html", title="More", current_section="More")


@home.route("/credits")
def credits():
    return render_template("credits.html", title="Credits", current_section="More")


@home.before_request
def before_request():
    endpoint = request.endpoint
    action = {
        "home.more": more,
        "home.credits": credits,
    }.get(endpoint, more)

    mmdb_promotion(action)()

src/manga/routes.py
import os
import random
import time
from datetime import datetime
import platform

from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    send_file,
    url_for,
)
from sqlalchemy import delete

from src import db
from src.home.utils import mmdb_promotion
from src.manga import web_scraper
from src.manga.backup import (
    export_mmdb_backup,
    import_anilist_manga,
    import_MangaUpdates_list,
    import_mmdb_backup,
    import_MyAnimeList_manga,
)
from src.manga.forms import MangaForm, MangaSearchBar
from src.manga.utils import (
    MangaHistory,
    get_layout,
    get_settings,
    remove_cover,
    save_picture,
)
from src.models import Manga

today_date = datetime.date(datetime.today())

manga = Blueprint("manga", __name__, url_prefix="/manga")


@manga.route("/list/all")
def manga_list():
    manga_list = Manga.query.order_by(Manga.title.name).all()
    settings = get_settings()
    layout = get_layout()
    return render_template(
        f"manga/{layout}",
        title="Manga List",
        current_section="Manga",
        manga_list=manga_list,
        sort_function="All",
        settings=settings,
    )


# Add New Manga
@manga.route("/new", methods=["GET", "POST"])
def add_manga():
    form = MangaForm()
    if form.validate_on_submit():
        # In linux if DateField is None(0001-01-01) it will be set to 0001-01-01
        if form.start_date.data == None:
            form.start_date.data = "0001-01-01"
        if form.end_date.data == None:
            form.end_date.data = "0001-01-01"
        if form.cover.data:
            picture_file = save_picture(form.cover.data)
        else:
            picture_file = "default-manga.svg"
        manga = Manga(
            title=form.title.data,
            cover=picture_file,
            start_date=form.start_date.data,
            end_date=form.end_date.data,
            volume=form.volume.data,
            chapter=form.chapter.data,
            status=form.status.data,
            score=form.score.data,
            description=form.description.data,
            genre=form.genre.data,
            tags=form.tags.data,
            author=form.author.data,
            artist=form.artist.data,
            notes=form.notes.data,
        )
        db.session.add(manga)
        db.session.commit()
        flash(f"{form.title.data} is added!", "success")
        return redirect(url_for("manga.manga_list"))
    return render_template(
        "manga/create-manga.html",
        title="New Manga",
        form=form,
        legend="New Manga",
        current_section="Manga",
    )


# Update a Manga
@manga.route("/edit/<int:manga_id>", methods=["GET", "POST"])
def edit_manga(manga_id):
    manga = Manga.query.get_or_404(manga_id)
    form = MangaForm()
    manga_history = MangaHistory()
    history = manga_history.get_history(manga.title)
    old_name = manga.title
    if form.validate_on_submit():
        # In linux if DateField is None(0001-01-01) it will be set to 0001-01-01
        if form.start_date.data == None:
            form.start_date.data = "0001-01-01"
        if form.end_date.data == None:
            form.end_date.data = "0001-01-01"
        if form.cover.data:
            remove_cover(manga.cover)
            picture_file = save_picture(form.cover.data)
            manga.cover = picture_file
        manga.title = form.title.data
        manga.start_date = form.start_date.data
        manga.end_date = form.end_date.data
        manga.volume = form.volume.data
        manga.chapter = form.chapter.data
        manga.status = form.status.data
        manga.score = form.score.data
        manga.description = form.description.data
        manga.genre = form.genre.data
        manga.tags = form.tags.data
        manga.author = form.author.data
        manga.artist = form.artist.data
        manga.notes = form.notes.data
        db.session.commit()
        manga_history.check_rename(old_name=old_name, new_name=form.title.data)
        manga_history.add_chapter(manga.title, form.chapter.data)
        flash("Your manga has been updated!", "success")
    elif request.method == "GET":
        form.title.data = manga.title
        form.start_date.data = datetime.strptime(manga.start_date, "%Y-%m-%d").date()
        form.end_date.data = datetime.strptime(manga.end_date, "%Y-%m-%d").date()
        form.volume.data = manga.volume
        form.chapter.data = manga.chapter
        form.status.data = manga.status
        form.score.data = str(manga.score)
        form.description.data = manga.description
        form.tags.data = manga.tags
        form.genre.data = manga.genre
        form.author.data = manga.author
        form.artist.data = manga.artist
        form.notes.data = manga.notes
    return render_template(
        "manga/edit-manga.html",
        title=f"Edit {manga.title}",
        form=form,
        manga=manga,
        legend="Update Manga",
        current_section="Manga",
        history=history,
        platform=platform
    )


# Updates metadata related to the manga
# manga_id = 0 means whole database will get updated
@manga.route("/function/update-metadata/<int:manga_id>")
def update_metadata(manga_id):
    if manga_id != 0:
        manga = Manga.query.get_or_404(manga_id)
        if manga.cover != "default-manga.svg":
            cover_path = f"src/static/manga_cover/{manga.cover}"
            if os.path.exists(cover_path):
                os.remove(cover_path)
        metadata = web_scraper.manga_search(manga.title)
        (
            manga.artist,
            manga.author,
            manga.cover,
            manga.description,
            manga.genre,
        ) = metadata
        db.session.commit()
    else:
        manga_list = Manga.query.order_by(Manga.title.name).all()
        for manga in manga_list:
            if manga.cover != "default-manga.svg":
                cover_path = f"src/static/manga_cover/{manga.cover}"
                if os.path.exists(cover_path):
                    os.remove(cover_path)
            time.sleep(random.randint(2, 5))
            metadata = web_scraper.manga_search(manga.title)
            (
                manga.artist,
                manga.author,
                manga.cover,
                manga.description,
                manga.genre,
            ) = metadata
            db.session.commit()
        return redirect(url_for("manga.manga_list"))
    return redirect(url_for("manga.edit_manga", manga_id=manga_id))


# Delete A Manga
@manga.route("/delete/<int:manga_id>", methods=["POST"])
def delete_manga(manga_id):
    manga = Manga.query.get_or_404(manga_id)
    manga_history = MangaHistory()
    remove_cover(manga.cover)
    db.session.delete(manga)
    db.session.commit()
    manga_history.clear_history(manga.title)
    flash("Your manga has been Obliterated!", "success")
    return redirect(url_for("manga.manga_list"))


# Sort Manga
@manga.route("/list/<string:sort_function>", methods=["GET", "POST"])
def sort_manga(sort_function):
    manga_list = (
        Manga.query.filter_by(status=sort_function).order_by(Manga.title.name).all()
    )
    settings = get_settings()
    layout = get_layout()
    return render_template(
        f"manga/{layout}",
        title=f"{sort_function} Manga",
        manga_list=manga_list,
        sort_function=sort_function,
        current_section="Manga",
        settings=settings,
    )


# Add One Chapter To The Manga
@manga.route("/add-one-chapter/<int:manga_id>")
def add_one_chapter(manga_id):
    manga_history = MangaHistory()
    manga = Manga.query.get_or_404(manga_id)
    manga.chapter = manga.chapter + 1
    db.session.commit()
    manga_history.add_chapter(manga.title, manga.chapter)
    return redirect(url_for("manga.manga_list"))


# Add One Volume To The Manga
@manga.route("/add-one-volume/<int:manga_id>")
def add_one_volume(manga_id):
    manga = Manga.query.get_or_404(manga_id)
    manga.volume = manga.volume + 1
    db.session.commit()
    return redirect(url_for("manga.manga_list"))


# Searches manga related to given genre in the database
@manga.route("/genre/<string:genre>", methods=["GET"])
def search_genre(genre):
    manga_list = Manga.query.filter(Manga.genre.like(f"%{genre}%")).all()
    settings = get_settings()
    layout = get_layout()
    return render_template(
        f"manga/{layout}",
        title=f"{genre} Genre",
        manga_list=manga_list,
        current_section="Manga",
        settings=settings,
    )


# Searches manga related to given tags in the database
@manga.route("/tags/<string:tag>", methods=["GET"])
def search_tags(tag):
    manga_list = Manga.query.filter(Manga.tags.like(f"%{tag}%")).all()
    settings = get_settings()
    layout = get_layout()
    return render_template(
        f"manga/{layout}",
        title=f"{tag} Tag",
        manga_list=manga_list,
        current_section="Manga",
        settings=settings,
    )


# The path for uploading the file
@manga.route("/import", methods=["GET", "POST"])
def import_manga():
    return render_template(
        "manga/import-manga.html", current_section="Manga", title="Import Manga"
    )


# Imports backup based on file extension
@manga.route("/import/<string:backup>", methods=["POST"])
def importbackup(backup):
    # get the file from the files object
    backup_file = request.files["file"]
    # Mapping file prefixes to status values for MangaUpdates
    prefix_to_status = {
        "read": "Reading",
        "wish": "Plan to read",
        "complete": "Completed",
        "unfinished": "Dropped",
        "hold": "On hold",
    }
    # Checking if no file is sent
    if backup_file.filename == "":
        flash("Choose a file to import!", "danger")
        return redirect(url_for("manga.import_manga"))
    # If file is sent through MMDB form, checking if file name is correct. If correct, then extracting the import
    elif (
        backup == "MyMangaDataBase"

src/templates/manga/import-manga.html
{% extends "layout.html" %}
{% block body %}
<div>
    <div class="content-section mx-1 my-3">
        <form action="{{ url_for('manga.importbackup', backup='MyMangaDataBase') }}" method="post"
            enctype="multipart/form-data">
            <div class="card bg-dark border-white">
                <div class="card-body">
                    <h5 class="card-title">MMDB Manga Import</h5>
                    <p class="card-text">Imports " MMDB-Manga-Export-{Date}.zip " file</p>
                    <div class="d-flex">
                        <input type="submit" class="me-3 btn btn-secondary btn-lg">
                        <input class="form-control form-control-lg" id="formFileLg" name="file" type="file" ,
                            accept=".zip">
                    </div>
                    <p class="mt-3 card-text text-warning">This wil overwrite all manga chapter logs!</p>
                </div>
            </div>
        </form>
    </div>
    <div class="content-section mx-1 my-3">
        <form action="{{ url_for('manga.importbackup', backup='MyAnimeList') }}" method="post"
            enctype="multipart/form-data">
            <div class="card bg-dark border-white">
                <div class="card-body">
                    <h5 class="card-title">MyAnimeList Manga Import</h5>
                    <p class="card-text">Imports " mangalist_{uuid}_-_{user_id}.xml " file</p>
                    <div class="d-flex">
                        <input type="submit" class="me-3 btn btn-secondary btn-lg">
                        <input class="form-control form-control-lg" id="formFileLg" name="file" type="file" ,
                            accept=".xml">
                    </div>
                    <p class="mt-3 card-text text-warning">Only import .xml file!</p>
                    <p class="mt-3 card-text text-info">NOTE:</p>
                    <ul class="card-text text-info">
                        <li>
                            Each entry will take between 1 to 2 seconds to get imported to avoid hitting
                            <a href="https://docs.api.jikan.moe/#section/Information/Rate-Limiting" target="_blank"
                                rel="noopener noreferrer">
                                api rate limit.
                            </a>
                        </li>
                        <li>
                            In Short - the bigger the list, more the time taken to import.
                        </li>
                        <li>
                            During import process, please wait until the page is redirected to
                            <i class="bi bi-book"></i> Manga List page.
                        </li>
                        <li>You can see the progress on server terminal (＾▽＾)</li>
                    </ul>
                </div>
            </div>
        </form>
    </div>
    <div class="content-section mx-1 my-3">
        <form action="{{ url_for('manga.importbackup', backup='MangaUpdates') }}" method="post"
            enctype="multipart/form-data">
            <div class="card bg-dark border-white">
                <div class="card-body">
                    <h5 class="card-title">MangaUpdates Import</h5>
                    <p class="card-text">Imports " {status}_{Date}.txt " file</p>
                    <div class="d-flex">
                        <input type="submit" class="me-3 btn btn-secondary btn-lg">
                        <input class="form-control form-control-lg" id="formFileLg" name="file" type="file" ,
                            accept=".txt">
                    </div>
                    <p class="mt-3 card-text text-warning">Custom lists are not supported.</p>
                </div>
            </div>
        </form>
    </div>
    <div class="content-section mx-1 my-3">
        <form action="{{ url_for('manga.importbackup', backup='AniList') }}" method="post"
            enctype="multipart/form-data">
            <div class="card bg-dark border-white">
                <div class="card-body">
                    <h5 class="card-title">AniList Import</h5>
                    <p class="card-text">Imports " gdpr_data.json " file</p>
                    <div class="d-flex">
                        <input type="submit" class="me-3 btn btn-secondary btn-lg">
                        <input class="form-control form-control-lg" id="formFileLg" name="file" type="file" ,
                            accept=".json">
                    </div>
                    <p class="mt-3 text-info">Uses AniList API to get metadata</p>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock body %}

src/templates/manga/manga-cards.html
{% extends 'layout.html' %}
{% block secondHeader %}
<!-- Secondary Header -->
<div>
    <header class="d-flex py-3">
        <!-- List Functions -->
        <ul class="nav nav-pills me-auto ms-2">
            <li class="nav-item"><a href="{{ url_for('manga.add_manga') }}" class="nav-link"><i class="bi bi-book"></i>
                    Add Manga</a></li>
            <li class="nav-item"><a href="{{ url_for('manga.import_manga') }}" class="nav-link"><i
                        class="bi bi-database-down"></i> Import</a></li>
            <li class="nav-item"><a href="{{ url_for('manga.export') }}" class="nav-link"><i
                        class="bi bi-database-up"></i> Export</a></li>
        </ul>
        <!-- Sort Functions -->
        <ul class="nav nav-pills mx-auto">
            {% if sort_function == "All" %}
            <li class="nav-item"><a href="{{ url_for('manga.manga_list') }}" class="nav-link active"
                    aria-current="page">All</a></li>
            {% else %}
            <li class="nav-item"><a href="{{ url_for('manga.manga_list') }}" class="nav-link">All</a></li>
            {% endif %}
            {% if sort_function == "Reading" %}
            <li class="nav-item"><a href="{{ url_for('manga.sort_manga', sort_function = 'Reading') }}"
                    class="nav-link active" aria-current="page">Reading</a></li>
            {% else %}
            <li class="nav-item"><a href="{{ url_for('manga.sort_manga', sort_function = 'Reading') }}"
                    class="nav-link">Reading</a></li>
            {% endif %}
            {% if sort_function == "Completed" %}
            <li class="nav-item"><a href="{{ url_for('manga.sort_manga', sort_function = 'Completed') }}"
                    class="nav-link active" aria-current="page">Completed</a></li>
            {% else %}
            <li class="nav-item"><a href="{{ url_for('manga.sort_manga', sort_function = 'Completed') }}"
                    class="nav-link">Completed</a></li>
            {% endif %}
            {% if sort_function == "On hold" %}
            <li class="nav-item"><a href="{{ url_for('manga.sort_manga', sort_function = 'On hold') }}"
                    class="nav-link active" aria-current="page">On Hold</a></li>
            {% else %}
            <li class="nav-item"><a href="{{ url_for('manga.sort_manga', sort_function = 'On hold') }}"
                    class="nav-link">On Hold</a></li>
            {% endif %}
            {% if sort_function == "Dropped" %}
            <li class="nav-item"><a href="{{ url_for('manga.sort_manga', sort_function = 'Dropped') }}"
                    class="nav-link active" aria-current="page">Dropped</a></li>
            {% else %}
            <li class="nav-item"><a href="{{ url_for('manga.sort_manga', sort_function = 'Dropped') }}"
                    class="nav-link">Dropped</a></li>
            {% endif %}
            {% if sort_function == "Plan to read" %}
            <li class="nav-item"><a href="{{ url_for('manga.sort_manga', sort_function = 'Plan to read') }}"
                    class="nav-link active" aria-current="page">Plan To Read</a></li>
            {% else %}
            <li class="nav-item"><a href="{{ url_for('manga.sort_manga', sort_function = 'Plan to read') }}"
                    class="nav-link">Plan To Read</a></li>
            {% endif %}
        </ul>
        <!-- Search Bar -->
        <form method="POST" action="{{ url_for('manga.search_manga')}}" class="d-flex ms-auto me-2">
            {{ manga_navsearch.hidden_tag() }}
            {{ manga_navsearch.search_field(class="form-control mx-1", placeholder=manga_title) }}
            {{ manga_navsearch.search_button(class="btn btn-outline-primary") }}
        </form>
    </header>
</div>
{% endblock %}

<!-- Flash messages go here which comes from layout.html -->

{% block body %}
<!-- Cards -->
{% if settings["layout"] == "Card" %}
<div id="masonary-id" class="row row-cols-3 g-4 ms-5 me-5 justify-content-center" data-masonry="{'percentPosition': true}">
    {% for manga in manga_list %}
    <div class="col masonary-class">
        <div class="card" style="max-width: 540px;">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="{{ url_for('static', filename='manga_cover/' + manga.cover) }}"
                        class="img-fluid rounded-start" alt="Anime Cover">
                </div>
                <div class="col-md-8">
                    <div class="card-body pb-0">
                        {% if settings["truncate_title"] == "Yes" %}
                        <h5 class="card-title text-truncate"><a class="text-decoration-underline text-reset"
                                href="{{ url_for('manga.edit_manga', manga_id=manga.id) }}">
                                {{ manga.title }}
                            </a></h5>
                        {% else %}
                        <h5 class="card-title"><a class="text-decoration-underline text-reset"
                                href="{{ url_for('manga.edit_manga', manga_id=manga.id) }}">
                                {{ manga.title }}
                            </a></h5>
                        {% endif %}
                        <p class="card-text">
                            Score: {{ manga.score }}
                        </p>
                        <div class="d-flex">
                            <p class="card-text">
                                Volumes:
                                <a href="{{ url_for('manga.add_one_volume', manga_id=manga.id) }}"
                                    class="text-decoration-underline text-reset">
                                    {{ manga.volume }}
                                </a>
                            </p>
                            &emsp;
                            <p class="card-text">
                                Chapters:
                                <a href="{{ url_for('manga.add_one_chapter', manga_id=manga.id) }}"
                                    class="text-decoration-underline text-reset">
                                    {{ manga.chapter }}
                                </a>
                            </p>
                        </div>
                        <p class="card-text">
                            Start Date:
                            {% if manga.start_date == "0001-01-01" %}
                            -
                            {% else %}
                            {{ manga.start_date }}
                            {% endif %}
                        </p>
                        <p class="card-text">
                            End Date:
                            {% if manga.end_date == "0001-01-01" %}
                            -
                            {% else %}
                            {{ manga.end_date }}
                            {% endif %}
                        </p>
                        <p class="card-text">Status: {{ manga.status }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<div class="container">
    <div id="masonary-id" class="row row-cols-1 row-cols-md-3" data-masonry='{"percentPosition": true }'>
        {% for manga in manga_list %}
        <div class="col my-2 masonary-class">
            <div class="card p-0 text-bg-dark" style="max-width: 540px; overflow: hidden;">
                <img src="{{ url_for('static', filename='manga_cover/' + manga.cover) }}" class="img-fluid row-md-4"
                    alt="Anime Cover" style="filter:blur(5px); -webkit-filter:blur(5px);">
                <div class="card-img-overlay" style="background-color: rgba(0,0,0, 0.4);">
                    <div class="card-body pb-0">
                        {% if settings["truncate_title"] == "Yes" %}
                        <h5 class="card-title text-truncate"><a class="text-decoration-underline text-reset"
                                href="{{ url_for('manga.edit_manga', manga_id=manga.id) }}">
                                {{ manga.title }}
                            </a></h5>
                        {% else %}
                        <h5 class="card-title"><a class="text-decoration-underline text-reset"
                                href="{{ url_for('manga.edit_manga', manga_id=manga.id) }}">
                                {{ manga.title }}
                            </a></h5>
                        {% endif %}
                        <p class="card-text">
                            Score: {{ manga.score }}
                        </p>
                        <div class="d-flex">
                            <p class="card-text">
                                Volumes:
                                <a href="{{ url_for('manga.add_one_volume', manga_id=manga.id) }}"
                                    class="text-decoration-underline text-reset">
                                    {{ manga.volume }}
                                </a>
                            </p>
                            &emsp;
                            <p class="card-text">
                                Chapters:
                                <a href="{{ url_for('manga.add_one_chapter', manga_id=manga.id) }}"
                                    class="text-decoration-underline text-reset">
                                    {{ manga.chapter }}
                                </a>
                            </p>
                        </div>
                        <p class="card-text">
                            Start Date:
                            {% if manga.start_date == "0001-01-01" %}
                            -
                            {% else %}
                            {{ manga.start_date }}
                            {% endif %}
                        </p>
                        <p class="card-text">
                            End Date:
                            {% if manga.end_date == "0001-01-01" %}
                            -
                            {% else %}
                            {{ manga.end_date }}
                            {% endif %}
                        </p>
                        <p class="card-text">Status: {{ manga.status }}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}
{% endblock body %}